routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('departments','departmentsController');
Route::resource('programs','programsController');
Route::resource('semesters','semestersController');
Route::resource('subjects','subjectsController');
Route::get('/mysubjects','subjectsController@mysubjects')->name('subjects.mysubjects');
Route::resource('papers','papersController');
Route::get('/mypapers','usersController@mypapers')->name('users.mypapers');

Route::resource('questions','questionsController');
Route::get('/teachers', 'usersController@teachers')->name('users.teachers');
Route::get('/hod', 'usersController@hod')->name('users.hod');
Route::get('/dashboard', 'dashboardController@index')->name('dashboard.index');

app/department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class department extends Model
{
    protected $fillable = ['department_name','hod'];

    public function head(){
        return $this->belongsTo(User::class,'hod');
    }
}

app/Http/Controllers/departmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\department;
use App\User;
use App\Http\Requests\departments\insert;
use App\Http\Requests\departments\update;
class departmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
        $this->middleware(['auth','can:admin']);
    }
    public function index()
    {
        return view('departments.index')->with('departments',department::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departments.create')
        ->with('teachers',User::where('role','teacher')->get());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(insert $request)
    {
     department::create([
        'department_name' => $request->department_name,
        'hod' => $request->department_hod
     ]);   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(department $department)
    {
        return view('departments.create')
        ->with('department',$department)
        ->with('teachers',User::where('role','teacher')->get());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(update $request,department $department)
    {
        if($department->hod == NULL && $request->department_hod == NULL){
            //do nothing
        }
        else if($department->hod == NULL && $request->department_hod != NULL){
            //change that teacher tole to hod
        }
        else if($department->hod != NULL && $request->department_hod == NULL){
            // change that hod role to teacher
        }
        else{
            // first make current hod role to teacher
            // then make selected teacher role to hod
        }     

        $department->update([
            'department_name' => $request->department_name,
            'hod' => $request->department_hod
         ]);  
         session()->flash('success','Department Updated Successfully');
         return redirect(route('departments.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/departments/create.blade.php
@extends('adminlte::page')

@section('content')
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">
                @if(isset($department))
                  Edit Department
                @else
                  Add Department
                @endif
                </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ isset($department) ? route('departments.update',$department->id) : route('departments.store') }}">
                  @csrf
                  @if(isset($department))
                    @method('PATCH')
                  @endif
                <div class="card-body">
                  <div class="form-group">
                    <label for="department_name">Department Name</label>
                    <input type="text" class="{{ $errors->has('department_name') ? 'is-invalid':'' }} form-control"
                     name="department_name" value="{{ isset($department) ? $department->department_name : '' }}" id="department_name" placeholder="Enter Department Name">
                    @if($errors->has('department_name'))
                    <span class="error invalid-feedback">{{ $errors->first('department_name') }}</span>
                    @endif
                  </div>
                  <div class="form-group">
                    <label for="departmentHOD">HOD</label><br />
                    <select class="select2" name="department_hod" id="">
                        <option value="">Leave it as for now</option>
                      @if(isset($department) && isset($department->head))
                      <option value="{{ $department->head->id }}" selected="selected" >{{ $department->head->name }}</option>
                      @endif
                    @forelse($teachers as $teacher)
                        <option value="{{ $teacher['id'] }}">{{ $teacher['name'] }}</option>    
                    @empty
                        <p>No Values to show</p>
                    @endforelse
                    </select>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">
                  @if(isset($department))
                    Update
                  @else
                    Add
                  @endif
                  </button>
                </div>
              </form>
            </div>
@endsection

@section('js')
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
  })
  </script>
@endsection

resources/views/departments/index.blade.php
@extends('adminlte::page')

@section('content')
   
<div class="card">
            <div class="card-header">
              <h2 class="card-title text-lg mb-0">Departments</h2>
              <a href="{{ route('departments.create') }}" class="btn btn-success text-white float-right">Add Department</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="department-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Rendering engine</th>
                  <th>Browser</th>
                  <th>Platform(s)</th>
                  <th>Engine version</th>
                  <th>CSS grade</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($departments as $department)
                    <tr>
                        <td>{{ $department['department_name'] }}</td>
                        <td>
                        @if(!$department['hod'])
                        <a href="{{ route('departments.edit',$department['id']) }}" class="btn btn-warning align-center">Assign HOD</a>
                        @else
                          {{ $department->head->name }}
                        @endif
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    @endforeach
                <tr>
                  <td>Trident</td>
                  <td>Internet
                    Explorer 4.0
                  </td>
                  <td>Win 95+</td>
                  <td> 4</td>
                  <td>X</td>
                </tr>
                <tr>
                  <td>Trident</td>
                  <td>Internet
                    Explorer 5.0
                  </td>
                  <td>Win 95+</td>
                  <td>5</td>
                  <td>C</td>
                </tr>
                <tr>
                  <td>Trident</td>
                  <td>Internet
                    Explorer 5.5
                  </td>
                  <td>Win 95+</td>
                  <td>5.5</td>
                  <td>A</td>
                </tr>
                <tr>
                  <td>Trident</td>
                  <td>Internet
                    Explorer 6
                  </td>
                  <td>Win 98+</td>
                  <td>6</td>
                  <td>A</td>
                </tr>
                <tr>
                  <td>Trident</td>
                  <td>Internet Explorer 7</td>
                  <td>Win XP SP2+</td>
                  <td>7</td>
                  <td>A</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                  <th>Rendering engine</th>
                  <th>Browser</th>
                  <th>Platform(s)</th>
                  <th>Engine version</th>
                  <th>CSS grade</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
@stop

@section('js')
<script>
        $(document).ready(function () {
            $('#department-table').dataTable();
        });
    </script>
@stop